name = input("Enter a string")
phone_number=input("Enter a phone number")

result=len(name)
first=name.find(" ")
last=name.rfind("a")
capital=name.capitalize()
name_upper=name.upper()
name_lower=name.lower()
is_digit=name.isdigit()
is_alpha=name.isalpha()
dash=phone_number.count("-")
dash_replace=phone_number.replace("-","")

print(result)
print(first)
print(last)
print(capital)
print(name_upper)
print(name_lower)
print(is_digit)
print(is_alpha)
print(dash)
print(dash_replace)
